// <auto-generated />
using System;
using IRL.VerticalSlices.APP.Common.Database.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IRL.VerticalSlices.APP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IRL.VerticalSlices.APP.Features.FinanceAccounts.Shared.DatabaseModels.FinanceAccountDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccountCode")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AccountCode")
                        .IsUnique();

                    b.HasIndex("CustomerCode");

                    b.ToTable("FinanceAccounts");
                });

            modelBuilder.Entity("IRL.VerticalSlices.APP.Features.FinanceAccounts.Shared.DatabaseModels.FinanceTransactionDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccountCode")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountCode");

                    b.ToTable("FinanceTransactions");
                });

            modelBuilder.Entity("IRL.VerticalSlices.APP.Features.FinanceAccounts.Shared.DatabaseModels.FinanceTransactionDbModel", b =>
                {
                    b.HasOne("IRL.VerticalSlices.APP.Features.FinanceAccounts.Shared.DatabaseModels.FinanceAccountDbModel", null)
                        .WithMany("FinanceTransactions")
                        .HasForeignKey("AccountCode")
                        .HasPrincipalKey("AccountCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IRL.VerticalSlices.APP.Features.FinanceAccounts.Shared.DatabaseModels.FinanceAccountDbModel", b =>
                {
                    b.Navigation("FinanceTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
